services:
  app:
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_URL=${BASE_URL}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
    working_dir: /app
    ports:
      - '3000:3000'
    image: esia-gallery
    env_file:
      - .env
